### ISSUE TITLE
zdb 2.0.0 failed to read raft log from version 8.2.*

### ISSUE THREAD

**Issue by deepthidevaki** [Zelldon/zdb#317] opened 2023-10-30 08:01 UTC
This was during a customer support. I don't remember the exact Zeebe version.I suspect it was due to the journal version change. It reported error on reading journal descriptor. 

Work around was to download an older release of zdb. So not a big issue, but would be nice if we can always use latest zdb release.

**Comment by Zelldon** [comment] 2023-10-30 08:19
@deepthidevaki Interesting. Can you share the state data folder? 

Because I recently added tests for 8.1, 8.2, 8.3, and snapshot so I can imagine why this fails? 🤔

**Comment by Zelldon** [comment] 2023-10-30 09:20
Can reproduce it with benchmark data for 8.2.x release.

```io.camunda.zeebe.journal.CorruptedJournalException: Couldn't read or recognize version of segment 'raft-partition-partition-1-363917.log'.
	at io.zell.zdb.journal.file.SegmentsManager.readDescriptor(SegmentsManager.java:162)
	at io.zell.zdb.journal.file.SegmentsManager.loadExistingSegment(SegmentsManager.java:201)
	at io.zell.zdb.journal.file.SegmentsManager.loadSegments(SegmentsManager.java:137)
	at io.zell.zdb.journal.file.SegmentsManager.open(SegmentsManager.java:105)
	at io.zell.zdb.journal.file.SegmentedReadOnlyJournal.<init>(SegmentedReadOnlyJournal.java:44)
	at io.zell.zdb.journal.file.SegmentedJournalBuilder.build(SegmentedJournalBuilder.java:109)
	at io.zell.zdb.log.LogFactory$Companion.newReader(LogFactory.kt:39)
	at io.zell.zdb.log.LogContentReader.<init>(LogContentReader.kt:31)
	at io.zell.zdb.journal.LogPrintCommand.call(LogPrintCommand.java:76)
	at io.zell.zdb.journal.LogPrintCommand.call(LogPrintCommand.java:27)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at io.zell.zdb.ZeebeDebugger.main(ZeebeDebugger.java:62)
Caused by: java.lang.IllegalStateException: Expected version to be one (2 2] but read 0 instead.
	at io.zell.zdb.journal.file.SegmentDescriptorReader.readFrom(SegmentDescriptorReader.java:46)
	at io.zell.zdb.journal.file.SegmentsManager.readDescriptor(SegmentsManager.java:154)
	... 18 more
```


What is weird is that we added recently 8.2 tests which don't fail.



I downloaded the release jar and it fails with the release data but not with the test data folder. There must be something wrong with the data generation as well. 🤔

**Comment by Zelldon** [comment] 2023-10-30 10:58
It looks like to fail always on the last segment, which might be created async? 🤔 



Can this be the case @deepthidevaki 



I downloaded data from release-8-2-x, which looks like this:

```
[cqjawa tmp/ cluster: zeebe-cluster ns:release-8-2-x]$ ls -la /tmp/data.bk/raft-partition/partitions/2/
total 1441804
drwxr-xr-x. 5 cqjawa cqjawa       380 Oct 30 11:54 .
drwxr-xr-x. 5 cqjawa cqjawa       100 Oct 30 11:53 ..
drwxr-xr-x. 2 cqjawa cqjawa        40 Oct 30 11:53 pending
-rw-r--r--. 1 cqjawa cqjawa 134217728 Oct 30 11:53 raft-partition-partition-2-371381.log
-rw-r--r--. 1 cqjawa cqjawa 134217728 Oct 30 11:53 raft-partition-partition-2-371382.log
-rw-r--r--. 1 cqjawa cqjawa 134217728 Oct 30 11:53 raft-partition-partition-2-371383.log
-rw-r--r--. 1 cqjawa cqjawa 134217728 Oct 30 11:53 raft-partition-partition-2-371384.log
-rw-r--r--. 1 cqjawa cqjawa 134217728 Oct 30 11:54 raft-partition-partition-2-371385.log
-rw-r--r--. 1 cqjawa cqjawa 134217728 Oct 30 11:53 raft-partition-partition-2-371386.log
-rw-r--r--. 1 cqjawa cqjawa 134217728 Oct 30 11:53 raft-partition-partition-2-371387.log
-rw-r--r--. 1 cqjawa cqjawa 134217728 Oct 30 11:53 raft-partition-partition-2-371388.log
-rw-r--r--. 1 cqjawa cqjawa 134217728 Oct 30 11:53 raft-partition-partition-2-371389.log
-rw-r--r--. 1 cqjawa cqjawa 134217728 Oct 30 11:53 raft-partition-partition-2-371390.log
-rw-r--r--. 1 cqjawa cqjawa 134217728 Oct 30 11:53 raft-partition-partition-2-371391.log
-rw-r--r--. 1 cqjawa cqjawa        78 Oct 30 11:53 raft-partition-partition-2.conf
-rw-r--r--. 1 cqjawa cqjawa         1 Oct 30 11:53 .raft-partition-partition-2.lock
-rw-r--r--. 1 cqjawa cqjawa       256 Oct 30 11:54 raft-partition-partition-2.meta
drwxr-xr-x. 2 cqjawa cqjawa       260 Oct 30 11:53 runtime
drwxr-xr-x. 3 cqjawa cqjawa        80 Oct 30 11:53 snapshots
[cqjawa tmp/ cluster: zeebe-cluster ns:release-8-2-x]$ ls -la /tmp/data.bk/raft-partition/partitions/3/
total 655372
drwxr-xr-x. 5 cqjawa cqjawa       260 Oct 30 11:52 .
drwxr-xr-x. 5 cqjawa cqjawa       100 Oct 30 11:53 ..
drwxr-xr-x. 2 cqjawa cqjawa        40 Oct 30 11:52 pending
-rw-r--r--. 1 cqjawa cqjawa 134217728 Oct 30 11:52 raft-partition-partition-3-366034.log
-rw-r--r--. 1 cqjawa cqjawa 134217728 Oct 30 11:52 raft-partition-partition-3-366035.log
-rw-r--r--. 1 cqjawa cqjawa 134217728 Oct 30 11:52 raft-partition-partition-3-366036.log
-rw-r--r--. 1 cqjawa cqjawa 134217728 Oct 30 11:52 raft-partition-partition-3-366037.log
-rw-r--r--. 1 cqjawa cqjawa 134217728 Oct 30 11:52 raft-partition-partition-3-366038.log
-rw-r--r--. 1 cqjawa cqjawa        78 Oct 30 11:52 raft-partition-partition-3.conf
-rw-r--r--. 1 cqjawa cqjawa         1 Oct 30 11:52 .raft-partition-partition-3.lock
-rw-r--r--. 1 cqjawa cqjawa       256 Oct 30 11:52 raft-partition-partition-3.meta
drwxr-xr-x. 2 cqjawa cqjawa       260 Oct 30 11:52 runtime
drwxr-xr-x. 3 cqjawa cqjawa        80 Oct 30 11:52 snapshots

```

Both partition fail on the last file:


```
$ java -jar zdb.jar log status -p data.bk/raft-partition/partitions/3/

io.camunda.zeebe.journal.CorruptedJournalException: Couldn't read or recognize version of segment 'raft-partition-partition-3-366038.log'.
	at io.zell.zdb.journal.file.SegmentsManager.readDescriptor(SegmentsManager.java:162)
	at io.zell.zdb.journal.file.SegmentsManager.loadExistingSegment(SegmentsManager.java:201)
	at io.zell.zdb.journal.file.SegmentsManager.loadSegments(SegmentsManager.java:137)
	at io.zell.zdb.journal.file.SegmentsManager.open(SegmentsManager.java:105)
	at io.zell.zdb.journal.file.SegmentedReadOnlyJournal.<init>(SegmentedReadOnlyJournal.java:44)
	at io.zell.zdb.journal.file.SegmentedJournalBuilder.build(SegmentedJournalBuilder.java:109)
	at io.zell.zdb.log.LogFactory$Companion.newReader(LogFactory.kt:39)
	at io.zell.zdb.log.LogStatus.<init>(LogStatus.kt:23)
	at io.zell.zdb.journal.LogCommand.status(LogCommand.java:47)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2066)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at io.zell.zdb.ZeebeDebugger.main(ZeebeDebugger.java:62)
Caused by: java.lang.IllegalStateException: Expected version to be one (2 2] but read 0 instead.
	at io.zell.zdb.journal.file.SegmentDescriptorReader.readFrom(SegmentDescriptorReader.java:46)
	at io.zell.zdb.journal.file.SegmentsManager.readDescriptor(SegmentsManager.java:154)
	... 19 more

```



```
$ java -jar zdb.jar log status -p data.bk/raft-partition/partitions/2/

io.camunda.zeebe.journal.CorruptedJournalException: Couldn't read or recognize version of segment 'raft-partition-partition-2-371391.log'.
	at io.zell.zdb.journal.file.SegmentsManager.readDescriptor(SegmentsManager.java:162)
	at io.zell.zdb.journal.file.SegmentsManager.loadExistingSegment(SegmentsManager.java:201)
	at io.zell.zdb.journal.file.SegmentsManager.loadSegments(SegmentsManager.java:137)
	at io.zell.zdb.journal.file.SegmentsManager.open(SegmentsManager.java:105)
	at io.zell.zdb.journal.file.SegmentedReadOnlyJournal.<init>(SegmentedReadOnlyJournal.java:44)
	at io.zell.zdb.journal.file.SegmentedJournalBuilder.build(SegmentedJournalBuilder.java:109)
	at io.zell.zdb.log.LogFactory$Companion.newReader(LogFactory.kt:39)
	at io.zell.zdb.log.LogStatus.<init>(LogStatus.kt:23)
	at io.zell.zdb.journal.LogCommand.status(LogCommand.java:47)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2066)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at io.zell.zdb.ZeebeDebugger.main(ZeebeDebugger.java:62)
Caused by: java.lang.IllegalStateException: Expected version to be one (2 2] but read 0 instead.
	at io.zell.zdb.journal.file.SegmentDescriptorReader.readFrom(SegmentDescriptorReader.java:46)
	at io.zell.zdb.journal.file.SegmentsManager.readDescriptor(SegmentsManager.java:154)
	... 19 more

```


In my tests I only have one file:

```
$ ls -la /tmp/data-io.zell.zdb.v82.Version82Test\$ZeebeStateTest--2496468440263260696/raft-partition/partitions/1/
total 131084
drwxr-xr-x. 5 cqjawa cqjawa       180 Oct 30 10:13 .
drwxr-xr-x. 3 cqjawa cqjawa        60 Oct 30 10:13 ..
drwxr-xr-x. 2 cqjawa cqjawa        40 Oct 30 10:13 pending
-rw-r--r--. 1 cqjawa cqjawa 134217728 Oct 30 10:13 raft-partition-partition-1-1.log
-rw-r--r--. 1 cqjawa cqjawa        50 Oct 30 10:13 raft-partition-partition-1.conf
-rw-r--r--. 1 cqjawa cqjawa         1 Oct 30 10:13 .raft-partition-partition-1.lock
-rw-r--r--. 1 cqjawa cqjawa       256 Oct 30 10:14 raft-partition-partition-1.meta
drwxr-xr-x. 2 cqjawa cqjawa       180 Oct 30 10:13 runtime
drwxr-xr-x. 2 cqjawa cqjawa        40 Oct 30 10:13 snapshots
```

**Comment by Zelldon** [comment] 2023-10-30 11:03
Ok when I generate more data in my tests I'm able to reproduce this.

**Comment by Zelldon** [comment] 2023-10-31 11:16
closed by https://github.com/Zelldon/zdb/pull/319

**Closed by Zelldon** 2023-10-31 11:16 UTC
